//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkBook
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Page
    {
        [Key]
        public int PageID { get; set; }
        [Required(ErrorMessage = "Page content is required.")]
        [StringLength(50, ErrorMessage = "Page content cannot be longer than 200 characters.")]
        [Display(Name = "Page Item")]
        public string PContent { get; set; }
        public int PBookID { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
